# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/my-first-blog"

# 网页的标题
title: "陈梦滢的小世界"
username: Crace
# 网站副标题
description: "支持女性在科技领域的发展（UNDP HERstory 活动）"


# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
