# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/my-first-blog"

# ç½‘é¡µçš„æ ‡é¢˜
title: "é™ˆæ¢¦æ»¢çš„å°ä¸–ç•Œ"
username: Crace
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "æ”¯æŒå¥³æ€§åœ¨ç§‘æŠ€é¢†åŸŸçš„å‘å±•ï¼ˆUNDP HERstory æ´»åŠ¨ï¼‰"

aboutme: "æˆ‘çš„ç”Ÿæ´»ï¼Œå·¥ä½œ ğŸ˜‰ğŸ•ğŸ§"

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
